Fix lint (#4)

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -68,4 +68,17 @@ jobs:
         run: make test-staticcheck
 
       - name: Lint
-        run: make test-lint lint_o="-set_exit_status"
+        run: make test-lint
+
+      - name: Format
+        run: |
+          if [ ! "$(gofmt -l . | grep -v "vendor/" | wc -l)" -eq 0 ]; then
+              # Create file annotations
+              echo "::error::Following files need formatting:"
+              gofmt -l . | grep -v "vendor/" | while read line ; do echo "::error file=$line::$line is wrongly formatted" ; done;
+              exit 1;
+          fi
+          echo "All source files correctly formatted 👌"
+          exit 0
+
+
